-- Enable Row Level Security on all tables
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE diagnosis_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE battery_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE spare_part_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE obd_inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE garage_demo_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE community_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE contact_inquiries ENABLE ROW LEVEL SECURITY;
